server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip сжатие для ускорения загрузки
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Пытаемся найти файл. Если его нет — отдаем index.html (для работы React Router)
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статических ассетов (картинок, шрифтов, собранных js/css)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webp)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
